name: Update and Release Manifest

on:
  release:
    # Triggers when you publish a new release in GitHub
    types: [published]

# This permission is required for the action to upload the file to your release
permissions:
  contents: write

jobs:
  release-manifest:
    runs-on: ubuntu-latest
    steps:
      # 1. Get your repository's code
      - name: Checkout repository code
        uses: actions/checkout@v4

      # 2. Update the version number in module.json
      - name: Update module.json version
        run: |
          TAG=${{ github.event.release.tag_name }}
          VERSION=${TAG#v}
          jq --arg new_version "$VERSION" '.version = $new_version' module.json > module.json.tmp && mv module.json.tmp module.json
          echo "Updated module.json to version $VERSION"

      # 3. Upload the updated module.json file to the release
      - name: Upload updated manifest to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./module.json"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      # 4. NEW: Announce the new version to the Foundry VTT website
      - name: Publish Module to FoundryVTT Website
        uses: cs96and/FoundryVTT-release-package@v1
        with:
          # This requires the PACKAGE_TOKEN secret to be set in your repository
          package-token: ${{ secrets.PACKAGE_TOKEN }}
          # This generates the URL to the manifest file you just uploaded
          manifest-url: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.json
